// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.0
// source: env/env.proto

package env

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Env Env
type Env int32

const (
	// UNDEFINED 未定义
	Env_UNDEFINED Env = 0
	// DEV 开发环境
	Env_DEV Env = 1
	// QA 测试环境
	Env_QA Env = 2
	// PL 预生产环境
	Env_PL Env = 3
	// ONLINE 线上环境
	Env_ONLINE Env = 4
	// ENV_FAT 功能验收测试环境
	Env_FAT Env = 5
	// PERF_TEST 压测环境
	Env_PERF_TEST Env = 6
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "UNDEFINED",
		1: "DEV",
		2: "QA",
		3: "PL",
		4: "ONLINE",
		5: "FAT",
		6: "PERF_TEST",
	}
	Env_value = map[string]int32{
		"UNDEFINED": 0,
		"DEV":       1,
		"QA":        2,
		"PL":        3,
		"ONLINE":    4,
		"FAT":       5,
		"PERF_TEST": 6,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_env_env_proto_enumTypes[0].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_env_env_proto_enumTypes[0]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_env_env_proto_rawDescGZIP(), []int{0}
}

var File_env_env_proto protoreflect.FileDescriptor

var file_env_env_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x2f, 0x65, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x65, 0x6e, 0x76, 0x2a, 0x51, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45,
	0x56, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x41, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x50,
	0x4c, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x41, 0x54, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x52, 0x46,
	0x5f, 0x54, 0x45, 0x53, 0x54, 0x10, 0x06, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x77, 0x71, 0x2d, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x67,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x76, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_env_env_proto_rawDescOnce sync.Once
	file_env_env_proto_rawDescData = file_env_env_proto_rawDesc
)

func file_env_env_proto_rawDescGZIP() []byte {
	file_env_env_proto_rawDescOnce.Do(func() {
		file_env_env_proto_rawDescData = protoimpl.X.CompressGZIP(file_env_env_proto_rawDescData)
	})
	return file_env_env_proto_rawDescData
}

var file_env_env_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_env_env_proto_goTypes = []interface{}{
	(Env)(0), // 0: env.Env
}
var file_env_env_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_env_env_proto_init() }
func file_env_env_proto_init() {
	if File_env_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_env_env_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_env_env_proto_goTypes,
		DependencyIndexes: file_env_env_proto_depIdxs,
		EnumInfos:         file_env_env_proto_enumTypes,
	}.Build()
	File_env_env_proto = out.File
	file_env_env_proto_rawDesc = nil
	file_env_env_proto_goTypes = nil
	file_env_env_proto_depIdxs = nil
}
